# Dependabot configuration for ProofOfFit
# This configuration enables automated dependency updates and security alerts

version: 2
updates:
  # Enable version updates for npm packages in the root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    assignees:
      - "engabire"
    reviewers:
      - "engabire"
    labels:
      - "dependencies"
      - "automated"
      - "do-not-deploy"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Enable version updates for npm packages in the web app
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    assignees:
      - "security-team"
    reviewers:
      - "engabire"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"
      - "do-not-deploy"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    # Group updates to reduce PR noise
    groups:
      # Group all security updates together
      security-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group minor and patch updates for common packages
      minor-updates:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for npm packages in the UI package
  - package-ecosystem: "npm"
    directory: "/packages/ui/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    assignees:
      - "engabire"
    reviewers:
      - "engabire"
    labels:
      - "dependencies"
      - "automated"
      - "do-not-deploy"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    assignees:
      - "security-team"
    reviewers:
      - "engabire"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"
      - "automated"
      - "do-not-deploy"

  # Enable version updates for Docker (if using Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    assignees:
      - "security-team"
    reviewers:
      - "engabire"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"
      - "automated"
      - "do-not-deploy"

  # Enable version updates for Terraform (if using Terraform)
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    assignees:
      - "security-team"
    reviewers:
      - "engabire"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "terraform"
      - "infrastructure"
      - "automated"
      - "do-not-deploy"

