# Gitleaks configuration for ProofOfFit repository
# This configuration helps detect secrets and sensitive information

title = "ProofOfFit Gitleaks Configuration"
version = "8.18.0"

# Enable entropy checks for better detection
[extend]
use_default = true

# Custom rules for ProofOfFit specific patterns
[[rules]]
id = "proofoffit-api-keys"
description = "ProofOfFit API Keys"
regex = '''(?i)(proofoffit|proof-of-fit).*?(api[_-]?key|secret|token)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["proofoffit", "api-key"]

[[rules]]
id = "supabase-keys"
description = "Supabase Keys"
regex = '''(?i)(supabase).*?(anon[_-]?key|service[_-]?role[_-]?key)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["supabase", "api-key"]

[[rules]]
id = "stripe-keys"
description = "Stripe Keys"
regex = '''(?i)(stripe).*?(secret[_-]?key|publishable[_-]?key)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["stripe", "api-key"]

[[rules]]
id = "vercel-tokens"
description = "Vercel Tokens"
regex = '''(?i)(vercel).*?(token|api[_-]?key)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["vercel", "api-key"]

[[rules]]
id = "github-tokens"
description = "GitHub Tokens"
regex = '''(?i)(github).*?(token|api[_-]?key)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["github", "api-key"]

[[rules]]
id = "database-urls"
description = "Database URLs"
regex = '''(?i)(database[_-]?url|db[_-]?url|connection[_-]?string)['":\s]*[a-zA-Z0-9+_\-\.]+://[a-zA-Z0-9+_\-\.]+:[a-zA-Z0-9+_\-\.]+@[a-zA-Z0-9+_\-\.]+:[0-9]+/[a-zA-Z0-9+_\-\.]+'''
tags = ["database", "connection-string"]

[[rules]]
id = "jwt-secrets"
description = "JWT Secrets"
regex = '''(?i)(jwt[_-]?secret|json[_-]?web[_-]?token[_-]?secret)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["jwt", "secret"]

[[rules]]
id = "encryption-keys"
description = "Encryption Keys"
regex = '''(?i)(encryption[_-]?key|cipher[_-]?key|aes[_-]?key)['":\s]*[a-zA-Z0-9]{20,}'''
tags = ["encryption", "key"]

# Exclude common false positives
[[rules.exclude]]
description = "Exclude test files"
regex = '''.*\.test\.(js|ts|tsx|jsx)$'''

[[rules.exclude]]
description = "Exclude example files"
regex = '''.*\.example\.(js|ts|tsx|jsx|json)$'''

[[rules.exclude]]
description = "Exclude documentation"
regex = '''.*\.md$'''

[[rules.exclude]]
description = "Exclude configuration files with examples"
regex = '''.*\.config\.(js|ts|json)$'''

# Global exclusions
[allowlist]
description = "Global allowlist for safe patterns"
regexes = [
  '''NEXT_PUBLIC_.*''',
  '''example\.supabase\.co''',
  '''your-.*-here''',
  '''^.*\.md$''',
  '''^.*\.txt$''',
  '''^.*\.example$''',
  '''^.*\.sample$''',
  '''^.*\.template$''',
  '''^.*\.config\.example$''',
  '''^.*\.env\.example$''',
  '''^.*\.env\.local\.example$''',
  '''^.*\.env\.sample$''',
  '''^.*\.env\.template$''',
  '''^.*test.*$''',
  '''^.*spec.*$''',
  '''^.*\.test\.(js|ts|tsx|jsx)$''',
  '''^.*\.spec\.(js|ts|tsx|jsx)$''',
  '''^.*\.stories\.(js|ts|tsx|jsx)$''',
  '''^.*\.config\.(js|ts|json)$''',
  '''^.*\.config\.example\.(js|ts|json)$''',
  '''^.*\.config\.sample\.(js|ts|json)$''',
  '''^.*\.config\.template\.(js|ts|json)$''',
  '''^.*\.example\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.sample\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.template\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.d\.ts$''',
  '''^.*\.lock$''',
  '''^.*\.log$''',
  '''^.*\.tmp$''',
  '''^.*\.temp$''',
  '''^.*\.cache$''',
  '''^.*\.gitignore$''',
  '''^.*\.dockerignore$''',
  '''^.*\.eslintignore$''',
  '''^.*\.prettierignore$''',
  '''^.*\.gitattributes$''',
  '''^.*\.editorconfig$''',
  '''^.*\.nvmrc$''',
  '''^.*\.node-version$''',
  '''^.*\.ruby-version$''',
  '''^.*\.python-version$''',
  '''^.*\.go-version$''',
  '''^.*\.rust-toolchain$''',
  '''^.*\.tool-versions$''',
  '''^.*\.versions$''',
  '''^.*\.version$''',
  '''^.*\.versionrc$''',
  '''^.*\.versionrc\.json$''',
  '''^.*\.versionrc\.js$''',
  '''^.*\.versionrc\.ts$''',
  '''^.*\.versionrc\.mjs$''',
  '''^.*\.versionrc\.cjs$''',
  '''^.*\.versionrc\.yml$''',
  '''^.*\.versionrc\.yaml$''',
  '''^.*\.versionrc\.toml$''',
  '''^.*\.versionrc\.ini$''',
  '''^.*\.versionrc\.cfg$''',
  '''^.*\.versionrc\.conf$''',
  '''^.*\.versionrc\.config$''',
  '''^.*\.versionrc\.config\.js$''',
  '''^.*\.versionrc\.config\.ts$''',
  '''^.*\.versionrc\.config\.mjs$''',
  '''^.*\.versionrc\.config\.cjs$''',
  '''^.*\.versionrc\.config\.yml$''',
  '''^.*\.versionrc\.config\.yaml$''',
  '''^.*\.versionrc\.config\.toml$''',
  '''^.*\.versionrc\.config\.ini$''',
  '''^.*\.versionrc\.config\.cfg$''',
  '''^.*\.versionrc\.config\.conf$''',
  '''^.*\.versionrc\.config\.config$''',
  '''^.*\.versionrc\.config\.config\.js$''',
  '''^.*\.versionrc\.config\.config\.ts$''',
  '''^.*\.versionrc\.config\.config\.mjs$''',
  '''^.*\.versionrc\.config\.config\.cjs$''',
  '''^.*\.versionrc\.config\.config\.yml$''',
  '''^.*\.versionrc\.config\.config\.yaml$''',
  '''^.*\.versionrc\.config\.config\.toml$''',
  '''^.*\.versionrc\.config\.config\.ini$''',
  '''^.*\.versionrc\.config\.config\.cfg$''',
  '''^.*\.versionrc\.config\.config\.conf$''',
  '''^.*\.versionrc\.config\.config\.config$'''
]

# File exclusions
files = [
  '''^.*\.md$''',
  '''^.*\.txt$''',
  '''^.*\.example$''',
  '''^.*\.sample$''',
  '''^.*\.template$''',
  '''^.*\.config\.example$''',
  '''^.*\.env\.example$''',
  '''^.*\.env\.local\.example$''',
  '''^.*\.env\.sample$''',
  '''^.*\.env\.template$''',
  '''^.*test.*$''',
  '''^.*spec.*$''',
  '''^.*\.test\.(js|ts|tsx|jsx)$''',
  '''^.*\.spec\.(js|ts|tsx|jsx)$''',
  '''^.*\.stories\.(js|ts|tsx|jsx)$''',
  '''^.*\.config\.(js|ts|json)$''',
  '''^.*\.config\.example\.(js|ts|json)$''',
  '''^.*\.config\.sample\.(js|ts|json)$''',
  '''^.*\.config\.template\.(js|ts|json)$''',
  '''^.*\.example\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.sample\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.template\.(js|ts|tsx|jsx|json)$''',
  '''^.*\.d\.ts$''',
  '''^.*\.lock$''',
  '''^.*\.log$''',
  '''^.*\.tmp$''',
  '''^.*\.temp$''',
  '''^.*\.cache$''',
  '''^.*\.gitignore$''',
  '''^.*\.dockerignore$''',
  '''^.*\.eslintignore$''',
  '''^.*\.prettierignore$''',
  '''^.*\.gitattributes$''',
  '''^.*\.editorconfig$''',
  '''^.*\.nvmrc$''',
  '''^.*\.node-version$''',
  '''^.*\.ruby-version$''',
  '''^.*\.python-version$''',
  '''^.*\.go-version$''',
  '''^.*\.rust-toolchain$''',
  '''^.*\.tool-versions$''',
  '''^.*\.versions$''',
  '''^.*\.version$''',
  '''^.*\.versionrc$''',
  '''^.*\.versionrc\.json$''',
  '''^.*\.versionrc\.js$''',
  '''^.*\.versionrc\.ts$''',
  '''^.*\.versionrc\.mjs$''',
  '''^.*\.versionrc\.cjs$''',
  '''^.*\.versionrc\.yml$''',
  '''^.*\.versionrc\.yaml$''',
  '''^.*\.versionrc\.toml$''',
  '''^.*\.versionrc\.ini$''',
  '''^.*\.versionrc\.cfg$''',
  '''^.*\.versionrc\.conf$''',
  '''^.*\.versionrc\.config$''',
  '''^.*\.versionrc\.config\.js$''',
  '''^.*\.versionrc\.config\.ts$''',
  '''^.*\.versionrc\.config\.mjs$''',
  '''^.*\.versionrc\.config\.cjs$''',
  '''^.*\.versionrc\.config\.yml$''',
  '''^.*\.versionrc\.config\.yaml$''',
  '''^.*\.versionrc\.config\.toml$''',
  '''^.*\.versionrc\.config\.ini$''',
  '''^.*\.versionrc\.config\.cfg$''',
  '''^.*\.versionrc\.config\.conf$''',
  '''^.*\.versionrc\.config\.config$''',
  '''^.*\.versionrc\.config\.config\.js$''',
  '''^.*\.versionrc\.config\.config\.ts$''',
  '''^.*\.versionrc\.config\.config\.mjs$''',
  '''^.*\.versionrc\.config\.config\.cjs$''',
  '''^.*\.versionrc\.config\.config\.yml$''',
  '''^.*\.versionrc\.config\.config\.yaml$''',
  '''^.*\.versionrc\.config\.config\.toml$''',
  '''^.*\.versionrc\.config\.config\.ini$''',
  '''^.*\.versionrc\.config\.config\.cfg$''',
  '''^.*\.versionrc\.config\.config\.conf$''',
  '''^.*\.versionrc\.config\.config\.config$'''
]

# Commit exclusions
commits = [
  '''^.*initial.*commit.*$''',
  '''^.*setup.*$''',
  '''^.*config.*$''',
  '''^.*example.*$''',
  '''^.*sample.*$''',
  '''^.*template.*$''',
  '''^.*test.*$''',
  '''^.*spec.*$''',
  '''^.*stories.*$''',
  '''^.*d\.ts.*$''',
  '''^.*lock.*$''',
  '''^.*log.*$''',
  '''^.*tmp.*$''',
  '''^.*temp.*$''',
  '''^.*cache.*$''',
  '''^.*gitignore.*$''',
  '''^.*dockerignore.*$''',
  '''^.*eslintignore.*$''',
  '''^.*prettierignore.*$''',
  '''^.*gitattributes.*$''',
  '''^.*editorconfig.*$''',
  '''^.*nvmrc.*$''',
  '''^.*node-version.*$''',
  '''^.*ruby-version.*$''',
  '''^.*python-version.*$''',
  '''^.*go-version.*$''',
  '''^.*rust-toolchain.*$''',
  '''^.*tool-versions.*$''',
  '''^.*versions.*$''',
  '''^.*version.*$''',
  '''^.*versionrc.*$''',
  '''^.*versionrc\.json.*$''',
  '''^.*versionrc\.js.*$''',
  '''^.*versionrc\.ts.*$''',
  '''^.*versionrc\.mjs.*$''',
  '''^.*versionrc\.cjs.*$''',
  '''^.*versionrc\.yml.*$''',
  '''^.*versionrc\.yaml.*$''',
  '''^.*versionrc\.toml.*$''',
  '''^.*versionrc\.ini.*$''',
  '''^.*versionrc\.cfg.*$''',
  '''^.*versionrc\.conf.*$''',
  '''^.*versionrc\.config.*$''',
  '''^.*versionrc\.config\.js.*$''',
  '''^.*versionrc\.config\.ts.*$''',
  '''^.*versionrc\.config\.mjs.*$''',
  '''^.*versionrc\.config\.cjs.*$''',
  '''^.*versionrc\.config\.yml.*$''',
  '''^.*versionrc\.config\.yaml.*$''',
  '''^.*versionrc\.config\.toml.*$''',
  '''^.*versionrc\.config\.ini.*$''',
  '''^.*versionrc\.config\.cfg.*$''',
  '''^.*versionrc\.config\.conf.*$''',
  '''^.*versionrc\.config\.config.*$''',
  '''^.*versionrc\.config\.config\.js.*$''',
  '''^.*versionrc\.config\.config\.ts.*$''',
  '''^.*versionrc\.config\.config\.mjs.*$''',
  '''^.*versionrc\.config\.config\.cjs.*$''',
  '''^.*versionrc\.config\.config\.yml.*$''',
  '''^.*versionrc\.config\.config\.yaml.*$''',
  '''^.*versionrc\.config\.config\.toml.*$''',
  '''^.*versionrc\.config\.config\.ini.*$''',
  '''^.*versionrc\.config\.config\.cfg.*$''',
  '''^.*versionrc\.config\.config\.conf.*$''',
  '''^.*versionrc\.config\.config\.config.*$'''
]