// Note: Do NOT mark the entire UI package as a client module.
// Individual components that require client features declare "use client" inside their own files.
// Core utilities
export { cn } from './lib/utils'

// UI Components
export { Button } from './components/button'
export { Button as ReusableButton } from './components/reusable-button'
export { Cta } from './components/cta'
export { CTAButton } from './components/cta-button' // compatibility
export { Breadcrumb } from './components/breadcrumb'
export type { BreadcrumbItem } from './components/breadcrumb'
export { Input } from './components/input'
export { Label } from './components/label'
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './components/card'
export { Badge } from './components/badge'
export { Avatar, AvatarFallback, AvatarImage } from './components/avatar'
export { Separator } from './components/separator'
export { Skeleton } from './components/skeleton'
export { Progress } from './components/progress'
export { Tabs, TabsContent, TabsList, TabsTrigger } from './components/tabs'
export { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from './components/dialog'
export { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from './components/sheet'
export { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from './components/dropdown-menu'
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/select'
export { Checkbox } from './components/checkbox'
export { RadioGroup, RadioGroupItem } from './components/radio-group'
export { Switch } from './components/switch'
export { Slider } from './components/slider'
export { Textarea } from './components/textarea'
export { Alert, AlertDescription, AlertTitle } from './components/alert'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from './components/alert-dialog'
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './components/tooltip'
export { Popover, PopoverContent, PopoverTrigger } from './components/popover'
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from './components/command'
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './components/accordion'
export { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, NavigationMenuViewport } from './components/navigation-menu'
export { ScrollArea, ScrollBar } from './components/scroll-area'
export { Toast, ToastAction, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport } from './components/toast'
export { Toaster } from './components/toaster'
export { NotificationCenter, useNotifications } from './components/notification-center'
export type { Notification } from './components/notification-center'
export { ErrorBoundary, useErrorHandler } from './components/error-boundary'
export { PerformanceMonitor } from './components/performance-monitor'
