import { Target, Proof } from "@prisma/client";

interface ReportLayoutProps {
  target: Target & {
    weights: Array<{
      proof: Proof;
      weight: number;
    }>;
  };
  proofs: Proof[];
}

export function ReportLayout({ target, proofs }: ReportLayoutProps) {
  const groupedProofs = proofs.reduce((acc, proof) => {
    if (!acc[proof.kind]) {
      acc[proof.kind] = [];
    }
    acc[proof.kind].push(proof);
    return acc;
  }, {} as Record<string, Proof[]>);

  return (
    <div className="max-w-4xl mx-auto p-8 print:p-4">
      <header className="mb-8 print:mb-4">
        <h1 className="text-3xl font-bold text-gray-900 print:text-2xl">
          {target.title}
        </h1>
        <p className="text-lg text-gray-600 print:text-base">
          {target.role} {target.companyHint && `at ${target.companyHint}`}
        </p>
        <div className="mt-4 text-sm text-gray-500 print:text-xs">
          Generated on {new Date().toLocaleDateString()}
        </div>
      </header>

      <main className="space-y-8 print:space-y-4">
        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4 print:text-xl">
            Evidence Summary
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 print:grid-cols-2">
            {Object.entries(groupedProofs).map(([kind, kindProofs]) => (
              <div key={kind} className="bg-gray-50 p-4 rounded-lg print:bg-white print:border">
                <h3 className="font-medium text-gray-900 capitalize mb-2">
                  {kind.replace("_", " ")} ({kindProofs.length})
                </h3>
                <ul className="space-y-1 text-sm text-gray-600">
                  {kindProofs.map((proof) => (
                    <li key={proof.id} className="flex items-start">
                      <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-2 flex-shrink-0" />
                      <div>
                        <div className="font-medium">{proof.title}</div>
                        {proof.summary && (
                          <div className="text-xs text-gray-500 mt-1">
                            {proof.summary}
                          </div>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4 print:text-xl">
            Detailed Evidence
          </h2>
          <div className="space-y-6 print:space-y-4">
            {proofs.map((proof) => (
              <div key={proof.id} className="border border-gray-200 rounded-lg p-6 print:border-gray-300">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-lg font-medium text-gray-900 print:text-base">
                    {proof.title}
                  </h3>
                  <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 print:bg-gray-100 print:text-gray-800">
                    {proof.kind}
                  </span>
                </div>
                
                {proof.summary && (
                  <p className="text-gray-600 mb-4 print:text-sm">
                    {proof.summary}
                  </p>
                )}
                
                {proof.url && (
                  <div className="flex items-center text-sm text-blue-600 print:text-blue-800">
                    <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    <a href={proof.url} target="_blank" rel="noopener noreferrer" className="hover:underline">
                      View Evidence
                    </a>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="mt-12 pt-8 border-t border-gray-200 print:mt-8 print:pt-4 print:border-gray-300">
        <div className="text-center text-sm text-gray-500 print:text-xs">
          <p>Generated by ProofOfFit - Evidence-based hiring intelligence</p>
          <p className="mt-1">Every claim cites a receipt. Every share is consent-locked.</p>
        </div>
      </footer>
    </div>
  );
}
