name: Enable Code Scanning

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  enable-code-scanning:
    name: Enable Code Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build UI package
        run: npm run build --workspace packages/ui

      - name: Build web application
        run: |
          export NEXT_PUBLIC_SUPABASE_URL="https://example.supabase.co"
          export NEXT_PUBLIC_SUPABASE_ANON_KEY="public-anon-key"
          npm run build --workspace web

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
