name: Lint Check

on:
  pull_request:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - ".eslintrc.json"
      - "package.json"

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint on web app
        run: npm run lint --workspace web

      - name: Run ESLint on UI package
        run: npm run lint --workspace @proof-of-fit/ui

      - name: Check TypeScript compilation
        run: npm run type-check --workspace web

      - name: Comment PR with lint results
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Lint Check Failed**\n\nPlease fix the linting errors before merging. Run `npm run lint` locally to see the issues.'
            })
