name: Storybook Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  storybook-build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
          retention-days: 3

  storybook-a11y:
    name: Storybook A11y Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Storybook test runner (vitest integration)
        run: npx storybook test --coverage --quiet || true

      - name: Upload test runner coverage (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-test-coverage
          path: coverage
          retention-days: 3
